- name: Adicionar entrada ao arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ dev_mysql_ip }} dev-mysql"
    state: present
    insertafter: EOF
  become: true
- name: Adicionar entrada ao arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ dev_mysql_ip }} dev-mysql"
    state: present
    insertafter: EOF
  become: true

- name: Clone todo-app
  ansible.builtin.git:
    repo: https://github.com/pcalves1/todo-app.git
    dest: /home/ubuntu/todo-app
    version: main
    force: true

- name: Install nodejs and npm
  apt:
    pkg:
      - nodejs
      - npm
    update_cache: true
  become: true

- name: Install packages based on package.json
  ansible.builtin.shell: |
    cd /home/ubuntu/todo-app; npm i

- name: Start project
  ansible.builtin.shell: 
    cmd: cd /home/ubuntu/todo-app && MYSQL_HOST="dev-mysql" MYSQL_ROOT_PASSWORD={{ mysql_password }} MYSQL_DATABASE="todo_items" MYSQL_USER={{ mysql_user }} npm run prod
