- name: Adicionar entrada ao arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ dev_mysql_ip }} dev-mysql"
    state: present
    insertafter: EOF
  become: true
- name: Adicionar entrada ao arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ dev_mysql_ip }} dev-mysql"
    state: present
    insertafter: EOF
  become: true

- name: Clone todo-app
  ansible.builtin.git:
    repo: https://github.com/pcalves1/todo-app.git
    dest: /home/ubuntu/todo-app
    version: main
    force: true

- name: Install nodejs and npm
  apt:
    pkg:
      - nodejs
      - npm
    update_cache: true
  become: true

- name: Install packages based on package.json
  ansible.builtin.shell: |
    cd /home/ubuntu/todo-app; npm i

# - name: Start porject
#   ansible.builtin.shell: |
#     cd /home/ubuntu/todo-app; ./deploy.sh

# - name: Echo my_env_var
  # vars_files:
  #   - vars.yaml
  # shell: "echo $MYSQL_HOST"
  # environment:
  #   MYSQL_HOST: "dev-mysql"
  #   MYSQL_ROOT_PASSWORD: "qwe@123"
  #   MYSQL_DATABASE: "todo_items"
  #   MYSQL_USER: "pcalves"

# - name: Start project
#   ansible.builtin.shell: 
#     cd /home/ubuntu/todo-app; npm run prod &
#   environment:
#     MYSQL_HOST: "dev-mysql"
#     MYSQL_ROOT_PASSWORD: "qwe@123"
#     MYSQL_DATABASE: "todo_items"
#     MYSQL_USER: "pcalves"

- name: Start project
  ansible.builtin.shell: 
    cmd: cd /home/ubuntu/todo-app && MYSQL_HOST="dev-mysql" MYSQL_ROOT_PASSWORD="qwe@123" MYSQL_DATABASE="todo_items" MYSQL_USER="pcalves" npm run prod


# - name: Start the application
#   environment:
#     MYSQL_HOST: "dev-mysql"
#     MYSQL_ROOT_PASSWORD: "qwe@123"
#     MYSQL_DATABASE: "todo_items"
#     MYSQL_USER: "pcalves"
#   command:
#     chdir: /home/ubuntu/todo-app
#     cmd: npm run prod