- name: Install mysql
  apt:
    pkg:
    - mysql-server
    - python3-pymysql
    update_cache: true
  become: true
  notify: 
    - restart mysql

- name: Create a new database with name "todo_items"
  community.mysql.mysql_db:
    name: "todo_items"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  become: true
  notify: 
    - restart mysql

- name: Create database user with name {{ mysql_user }} and password "*******" with all database privileges
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "todo_items.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    host: "{{ item }}"
  with_items:
  - "localhost"
  - "127.0.0.1"
  - "{{ todo_app_ip }}"
  become: true

- name: Configure database
  ansible.builtin.replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  become: true
  notify: 
    - restart mysql

